[package]
name = "termishade"
version = "0.1.0"
authors = ["Epsylon <eepsylon.3@gmail.com>"]
edition = "2018"

[dependencies]
alga = "0.9.3"
itertools = "0.9.0"

[dependencies.nalgebra]
version = "0.21.1"
features = ["alga"]
